import { ThemeManager } from "../themes.slint";

export component SearchBox {
    height: 40px;

    Rectangle {
        background: ThemeManager.is-dark ? rgba(0, 0, 0, 0.07) : rgba(255, 255, 255, 0.945);

        HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            spacing: 8px;

            Text {
                text: "搜索...";
                color: ThemeManager.is-dark ? rgba(255, 255, 255, 0.5) : rgba(0, 0, 0, 0.5);
                font-size: 12px;
                vertical-alignment: center;
            }
        }
    }
}